[package]
name = "dfr-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
daemonize = "0.5.0"
input-linux = { version = "0.7.1", features = ["serde"] }
input-linux-sys = "0.9.0"
libc = "0.2.171"
toml = "0.8.20"
